uploads = []
outputs = []

[[generated]]
id = "AWLqFoDOCqrhE_wJi2gIv"
uri = "file://artifacts/porsche-gt3rs/src/assets/hero.png"
type = "image"
title = "GT3 RS Hero"

[[generated]]
id = "fpK862Fc0i_AGskmcbWkt"
uri = "file://artifacts/porsche-gt3rs/src/assets/engine.png"
type = "image"
title = "GT3 RS Engine"

[[generated]]
id = "nF5mpPAMiFzb7iQ29griA"
uri = "file://artifacts/porsche-gt3rs/src/assets/aero.png"
type = "image"
title = "GT3 RS Aero"

[[generated]]
id = "ADcWAvOc_YgLKsBawa8Wh"
uri = "file://artifacts/porsche-gt3rs/src/assets/config_base.png"
type = "image"
title = "GT3 RS Config base"

[[generated]]
id = "Cs-Hnbo5Cd5XdiAhNW7oS"
uri = "file://artifacts/porsche-gt3rs/src/assets/gallery1.png"
type = "image"
title = "GT3 RS Gallery 1"

[[generated]]
id = "pAN32gQvWhnCz2rOmhSBs"
uri = "file://artifacts/porsche-gt3rs/src/assets/gallery2.png"
type = "image"
title = "GT3 RS Gallery 2"

[[generated]]
id = "13fBKNG6DbGN_dgglsVhM"
uri = "file://artifacts/porsche-gt3rs/src/assets/gallery3.png"
type = "image"
title = "GT3 RS Gallery 3"

[[generated]]
id = "ywZ-9M7f9EneUCWwNAiYs"
uri = "file://artifacts/porsche-gt3rs/src/assets/gallery4.png"
type = "image"
title = "GT3 RS Gallery 4"

[[generated]]
id = "tJTauvBTACdpUvn0GBhVJ"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_e322.png"
type = "image"
title = "generated_image"

[[generated]]
id = "grS2XrJW2QRd5i4za5iUP"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_f23f.png"
type = "image"
title = "generated_image"

[[generated]]
id = "H9DMAFj8n2AzhWBXNzB8c"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_590c.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fH0wPMfv3BWK2IXJAj0AA"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_6357.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ng1Pi7xCBPiuqioZF1zMu"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_d945.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mXkSg0KIWteZE_VSkRHDq"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_6235.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_3o-jWy1smkMnserUg97b"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_10ea.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OvSbXMzo2VEKIzjjVxAPf"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_585b.png"
type = "image"
title = "generated_image"

[[generated]]
id = "b0e0Jk2aXyUpWpU1pxG8_"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_f598.png"
type = "image"
title = "generated_image"

[[generated]]
id = "agoqx5-4mOKEYSosMghBL"
uri = "file://attached_assets/generated_images/porsche_911_gt3_rs_82ab.png"
type = "image"
title = "generated_image"
