name: Auto Version AT

on:
  push:
    branches:
      - testing

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-version:refname | head -n 1)

          if [ -z "$TAG" ]; then
            TAG="v1.0.0"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          VERSION=${{ steps.get_tag.outputs.tag }}
          VERSION=${VERSION#v}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}
